{% set version = "3.4.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-randomforestsrc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/randomForestSRC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/randomForestSRC/randomForestSRC_{{ version }}.tar.gz
  sha256: 0631eeeece5f9d3d7209e2650d73dded39ed9169eb267f52da6e3854f342eee6

build:
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-diagrammer
    - r-data.tree
  run:
    - r-base
    - r-diagrammer
    - r-data.tree

test:
  commands:
    - $R -e "library('randomForestSRC')"           # [not win]
    - "\"%R%\" -e \"library('randomForestSRC')\""  # [win]

about:
  home: http://web.ccs.miami.edu/~hishwaran http://www.kogalur.com https://github.com/kogalur/randomForestSRC
  license: GPL-3.0-or-later
  summary: Fast OpenMP parallel computing of Breiman's random forests for survival, competing risks, regression and classification based on Ishwaran and Kogalur's popular random survival forests (RSF) package.  Handles missing data and now includes multivariate, unsupervised forests, quantile regression and solutions for
    class imbalanced data.  New fast interface using subsampling and confidence regions for variable importance.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: randomForestSRC
# Version: 2.9.1
# Date: 2019-07-08
# Title: Fast Unified Random Forests for Survival, Regression, and Classification (RF-SRC)
# Author: Hemant Ishwaran <hemant.ishwaran@gmail.com>, Udaya B. Kogalur <ubk@kogalur.com>
# Maintainer: Udaya B. Kogalur <ubk@kogalur.com>
# BugReports: https://github.com/kogalur/randomForestSRC/issues/new
# Depends: R (>= 3.5.0),
# Imports: parallel
# Suggests: survival, pec, prodlim, mlbench, akima, caret, imbalance
# Description: Fast OpenMP parallel computing of Breiman's random forests for survival, competing risks, regression and classification based on Ishwaran and Kogalur's popular random survival forests (RSF) package.  Handles missing data and now includes multivariate, unsupervised forests, quantile regression and solutions for class imbalanced data.  New fast interface using subsampling and confidence regions for variable importance.
# License: GPL (>= 3)
# URL: http://web.ccs.miami.edu/~hishwaran http://www.kogalur.com https://github.com/kogalur/randomForestSRC
# NeedsCompilation: yes
# Packaged: 2019-07-08 18:25:47 UTC; kogalur
# Repository: CRAN
# Date/Publication: 2019-07-08 19:00:03 UTC
