{% set version = "2.14.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-randomforestsrc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/randomForestSRC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/randomForestSRC/randomForestSRC_{{ version }}.tar.gz
  sha256: 13a91dcefde2aa60337da8a04052255a9ecb35f4b777915dfbd0d80455d86e3b

build:
  merge_build_host: true  # [win]
  skip: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-diagrammer
    - r-data.tree
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-diagrammer
    - r-data.tree

test:
  commands:
    - $R -e "library('randomForestSRC')"           # [not win]
    - "\"%R%\" -e \"library('randomForestSRC')\""  # [win]

about:
  home: http://web.ccs.miami.edu/~hishwaran http://www.kogalur.com https://github.com/kogalur/randomForestSRC
  license: GPL-3.0-or-later
  summary: Fast OpenMP parallel computing of Breiman's random forests for survival, competing risks, regression and classification based on Ishwaran and Kogalur's popular random survival forests (RSF) package.  Handles missing data and now includes multivariate, unsupervised forests, quantile regression and solutions for
    class imbalanced data.  New fast interface using subsampling and confidence regions for variable importance.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: randomForestSRC
# Version: 2.9.1
# Date: 2019-07-08
# Title: Fast Unified Random Forests for Survival, Regression, and Classification (RF-SRC)
# Author: Hemant Ishwaran <hemant.ishwaran@gmail.com>, Udaya B. Kogalur <ubk@kogalur.com>
# Maintainer: Udaya B. Kogalur <ubk@kogalur.com>
# BugReports: https://github.com/kogalur/randomForestSRC/issues/new
# Depends: R (>= 3.5.0),
# Imports: parallel
# Suggests: survival, pec, prodlim, mlbench, akima, caret, imbalance
# Description: Fast OpenMP parallel computing of Breiman's random forests for survival, competing risks, regression and classification based on Ishwaran and Kogalur's popular random survival forests (RSF) package.  Handles missing data and now includes multivariate, unsupervised forests, quantile regression and solutions for class imbalanced data.  New fast interface using subsampling and confidence regions for variable importance.
# License: GPL (>= 3)
# URL: http://web.ccs.miami.edu/~hishwaran http://www.kogalur.com https://github.com/kogalur/randomForestSRC
# NeedsCompilation: yes
# Packaged: 2019-07-08 18:25:47 UTC; kogalur
# Repository: CRAN
# Date/Publication: 2019-07-08 19:00:03 UTC
