appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: gwRQyfJrE02xay0jzCJ2cFhz9i3eZH7GfaPx8fmKmMvH04ptTtC2eI5SA3x52WFrSvlsyJvEdSjx/JO1/nTBbVfpjWz3mQolp6xxxMpv6lwqcL79RoUYV0UIsV5v0vp+6LE8jf9HE13aWw9BkoMc7xG2fuQVIUu1IMYCvkIS7sWhwoQsGIJ9U8Gv7ij4j34571biQKI5Owr1jMFqZyW4YxBYgnwygIquAas2I0Yz6GXl1qVgBJR6rcfmqo50eZkBb1Zpu47KAztsiDvY1svApweXAEUP8Mfage/MQR5mclccxfUxINC1qByGDYJI8Kteoq6AOtwoHbANLu+WmAjjxLC4U149s0yfLQkaBAfLO+lJrBtZgblh0G9PdRNMpKHKF/uBaJZ+pERrodlzeL1/1iFw5NjBDlcVwfKTF07zk7B34QQ37fOIstVF4ObgPlX2F0qeZD+ItAyzzlBqKAf/KG4SJDV0Xn9sSDvglbILr4coanKS2APloxcD1RHvWp4Zd1UFGI036Xlc39ovkTevCqkH4yRL97IAUsO+yV9jAM0Dwx1md5HsTTz3jbMiDqEbJju26ZBHgfU2KmMV4U7f6ZRHd7VoQmaoj3iZf5ymN+djuhJ4G5d5+jn3puMUnci1pn2EbDIXnsD6SEiQ3Jxml3RxfvTGztqZlTewEoe/MDI=}
